### ISSUE TITLE
setting bindHttpPort to 0 crashes Arquillian

### ISSUE THREAD

**Issue by JianbaoTao** [arquillian/arquillian-container-tomcat#23]
Hi,

I wanted to use embedded-tomcat + Arquillian in my integration tests. Everything was fine when I ran the tests with only one process and the bindHttpPort was set to a reasonable number (12345, to be exact). However, as the number of tests grew, it became important to run the tests in parallel. Tomcat itself will pick a random port number if the port number is set to 0, which motivated me to set bindHttpPort to 0 in the first place. However, after doing that, I got a stacktrace like below:

```
java.net.NoRouteToHostException: Can't assign requested address
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at java.net.Socket.connect(Socket.java:528)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:996)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:932)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:850)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1300)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:468)
        at org.jboss.arquillian.protocol.servlet.ServletMethodExecutor.execute(ServletMethodExecutor.java:206)
        at org.jboss.arquillian.protocol.servlet.ServletMethodExecutor.access$000(ServletMethodExecutor.java:43)
        at org.jboss.arquillian.protocol.servlet.ServletMethodExecutor$1.run(ServletMethodExecutor.java:99)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
```

It appears to me that Arquillian uses the hard-coded bindHttpPort (i.e., 0) to invoke ServletMethodExecutor.execute, which apparently won't work in this case. 

So, is it possible to work around that? I am looking for a solution in which I can have Tomcat to use a random port, then retrieve it programmatically, and use it to construct  url in the tests.

Thank you very much.

**Comment by rhusar** [comment]
Thanks for the report @JianbaoTao, we will track this with https://github.com/arquillian/arquillian-container-tomcat/issues/115
